spring:
  application:
    name: gatekeeper
  datasource:
    url: jdbc:mysql://localhost:3306/gatekeeper?useSSL=false&serverTimezone=UTC
    username: root
    password: Sachin@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect